### ISSUE TITLE
An error occurred while running the game: Telemetry server is not disabled.

### ISSUE THREAD

**Issue by PopCat19** [NotThorny/Cultivation#12]
Occurs when attempting to launch through Cultivation UI. Grasscutter All-in-One is installed.
|
Where do I disable Telemetry server?

```rust
Set server to http://ps.yuuki.me:443
Connecting to proxy...
An error occurred while running the game: Telemetry server is not disabled: log-upload-os.hoyoverse.com
Game closed
Disconnecting from proxy...
```

<details>
<summary>full output</summary>

```rust
~/Cultivation FixedCultivation 10m 32s
❯ prime-run cultivation

** (cultivation:45584): WARNING **: 15:51:26.259: Disabled hardware acceleration because GTK failed to initialize GL: No available configurations for the given RGBA pixel format.

** (cultivation:45584): WARNING **: 15:51:26.317: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
Set server to http://ps.yuuki.me:443
Connecting to proxy...
An error occurred while running the game: Telemetry server is not disabled: log-upload-os.hoyoverse.com
Game closed
Disconnecting from proxy...
```

</details>

<details>
<summary>configuration.json</summary>

```json
{"toggle_grasscutter":true,"game_install_path":"/home/popcat19/.local/share/anime-game-launcher/Genshin Impact/GenshinImpact.exe","grasscutter_with_game":false,"grasscutter_path":"/home/popcat19/.local/share/cultivation/grasscutter/grasscutter.jar","java_path":"","close_action":0,"startup_launch":false,"last_ip":"ps.yuuki.me","last_port":"443","language":"en","custom_background":"","use_theme_background":false,"cert_generated":true,"theme":"default","https_enabled":false,"debug_enabled":false,"patch_rsa":true,"use_internal_proxy":true,"wipe_login":false,"horny_mode":false,"auto_mongodb":false,"un_elevated":false,"redirect_more":false,"grasscutter_elevation":"None","launch_args":""}
```

</details>

**Comment by NotThorny** [comment]
This sort of thing shouldn't be preventing the game from launching, my guess would be something inside the patch - although I've never seen this specific output before. Is this from trying to use a 5.0 client?

**Comment by PopCat19** [comment]
This is 4.0.1 with a manual patch dll replaced from GS Cultivation 1.2.0.
|
I'll see if it'll work without the manual patch dll.

**Comment by PopCat19** [comment]
> This is 4.0.1 with a manual patch dll replaced from GS Cultivation 1.2.0. | I'll see if it'll work without the manual patch dll.

Copied `mhypbase.dll` from working official game. When attempting to launch, Cultivation renames the dll to `mhypbase.dll.bak` and still outputs:
```rust
~/Cultivation FixedCultivation 1m
❯ prime-run cultivation

** (cultivation:66588): WARNING **: 16:16:16.713: Disabled hardware acceleration because GTK failed to initialize GL: No available configurations for the given RGBA pixel format.

** (cultivation:66588): WARNING **: 16:16:16.777: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
Renamed /home/popcat19/.local/share/anime-game-launcher/Genshin Impact/mhypbase.dll to /home/popcat19/.local/share/anime-game-launcher/Genshin Impact/mhypbase.dll.bak
Set server to http://ps.yuuki.me:443
Connecting to proxy...
An error occurred while running the game: Telemetry server is not disabled: log-upload-os.hoyoverse.com
Game closed
Disconnecting from proxy...
Error: No such file or directory (os error 2)
```

<details>
<summary>directory</summary>

```fish
~/.local/share/anime-game-launcher/Genshin Impact
❯ ls -l
drwxr-xr-x    - popcat19  5 Sep 18:41  GenshinImpact_Data
.rw-r--r-- 5.4M popcat19 21 Aug  2023  GenshinImpact.exe
.rw-r--r-- 3.7M popcat19 30 Mar  2023  HoYoKProtect.sys
.rwxr-xr-x  24M popcat19 28 Aug 07:36  mhypbase.dll.bak
.rw-r--r-- 2.1M popcat19 30 Aug  2022  mhyprot3.Sys
.rw-r--r-- 1.9M popcat19 21 Aug  2023  pkg_version
.rw-r--r--  37M popcat19 21 Aug  2023  UnityPlayer.dll
```

**Comment by NotThorny** [comment]
Is Cultivation not adding in a new mhypbase.dll file after renaming the original? It should be either replacing or renaming and then replacing the mhypbase.dll file.

**Comment by PopCat19** [comment]
No, at least not what I would've seen in `~/.local/share/anime-game-launcher/Genshin Impact/`.
|
Cultivation only renames the official dll as `mhypbase.dll.bak` without reverting, even after closing its runtime:
![image](https://github.com/user-attachments/assets/764e63d3-9138-4a0b-a30c-bbd228740bc3)

**Comment by NotThorny** [comment]
In your Cultivation install directory, or build path, find the folder called `patch` and take `version.dll` from there. Place it into the game folder and rename it to `mhypbase.dll` and then try again. Make sure you are getting the one just called `version.dll` not one of the ones with numbers.

**Comment by PopCat19** [comment]
Copied and renamed `version.dll` to `mhypbase.dll` from `~/Cultivation/src-tauri/target/release/patch/` to `.local/share/anime-game-launcher/Genshin Impact/`
|
Cultivation deletes patch `mhypbase.dll` or overrides back to `mhypbase.dll.bak` shortly after attempting to launch the game.

The output is still similar, except with line 1:
```rust
The game is already patched.
Set server to http://ps.yuuki.me:443
Connecting to proxy...
An error occurred while running the game: Telemetry server is not disabled: log-upload-os.hoyoverse.com
Game closed
Disconnecting from proxy...
```

**Comment by NotThorny** [comment]
Definitely an issue with the patching then, disable automatic RSA patching in Cultivation settings and copy over and rename `version.dll` again.

**Comment by PopCat19** [comment]
> Copied and renamed `version.dll` to `mhypbase.dll` from `~/Cultivation/src-tauri/target/release/patch/` to `.local/share/anime-game-launcher/Genshin Impact/`

![image](https://github.com/user-attachments/assets/d96ed8bb-ae4b-410b-a0b3-9abfba9db73e)
```
Set server to http://ps.yuuki.me:443
Connecting to proxy...
An error occurred while running the game: Telemetry server is not disabled: log-upload-os.hoyoverse.com
Game closed
Disconnecting from proxy...
```

This time, mhypbase.dll stays:
![image](https://github.com/user-attachments/assets/d547c1b4-9293-4bdc-bb2f-58055adcf443)

**Comment by NotThorny** [comment]
The only other option I would typically see here is if the game itself has an issue, such as not being fully extracted, or missing some files. Can you confirm the game launches as expected without Cultivation? The game folder should be around 56GB without voice data.

**Comment by PopCat19** [comment]
The game (login screen) runs fine under lutris:
![image](https://github.com/user-attachments/assets/4cd5ef58-d155-48e9-9494-85603b436d20)
![Screenshot_20240911_183004](https://github.com/user-attachments/assets/a8de9c34-d3c1-4ab2-8162-ba7fa7e12b4d)
|
The game also removes `mhypbase.dll.bak` upon launch. `mhypbase.dll.babak` is the patch dll that I've renamed before running through lutris.
```fish
~/.local/share/anime-game-launcher/Genshin Impact
❯ ls -l
drwxr-xr-x    - popcat19 11 Sep 18:26  GenshinImpact_Data
drwx------    - popcat19 11 Sep 18:26  GLCache
.rw-r--r-- 5.4M popcat19 21 Aug  2023  GenshinImpact.exe
.rw-r--r-- 3.7M popcat19 30 Mar  2023  HoYoKProtect.sys
.rwxr-xr-x  24M popcat19 28 Aug 07:36  mhypbase.dll
.rw-r--r--  87k popcat19  8 Sep 23:40  mhypbase.dll.babak
.rw-r--r-- 2.1M popcat19 30 Aug  2022  mhyprot3.Sys
.rw-r--r-- 1.9M popcat19 21 Aug  2023  pkg_version
.rw-r--r--  37M popcat19 21 Aug  2023  UnityPlayer.dll

```

**Comment by NotThorny** [comment]
I had to double check since this isn't something that would affect Cultivation or the patch, it appears this error is coming from the AAGL side instead.

**Comment by PopCat19** [comment]
I downloaded the 5.0.0 game files to disable telemetry through AAGL, then repaired the game data to be able to run it under lutris normally.
|
The game finally runs with Cultivation, but only with Auto RSA Patch disabled for now.
