### ISSUE TITLE
Update 4.7 path

### ISSUE THREAD

**Issue by AzureXuanVerse** [NotThorny/Cultivation#6]
Please update the 4.7 patch, thank you very much

**Comment by NotThorny** [comment]
I don't have a 4.7 client to test with currently, but you can make Cultivation use the 4.7 patch if it is different and you have one already. 
Go to your Cultivation install folder, default `C:\Program Files\Cultivation\` and then go to the `\patch` folder. Inside is a couple files, you want to replace `46version.dll` with your 4.7 patch. Make sure your new patch file is named as `46version.dll` still. Cultivation will then use that file to patch games that are newer than 4.5.

**Comment by NotThorny** [comment]
Added in 1.4.3.
