### ISSUE TITLE
请问这个使用的是yuanshen4.7吗？

### ISSUE THREAD

**Issue by try1995** [NotThorny/Cultivation#7]
我下载的是yuanshen4.0，发现启动还是官方登陆界面。可以给一个yuanshen包的下载地址吗

**Comment by try1995** [comment]
thread '<unnamed>' panicked at src\modules\address.rs:20:47:
index out of bounds: the len is 1 but the index is 1
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
url fetch responce: {"code":0,"message":"app running","milliTs":"1724490930762"}
url fetch responce: {"code":0,"message":"OK"}
url fetch responce: {"retcode":0,"message":"success","data":null}
url fetch responce: {"code":0,"message":"OK"}
url fetch responce: {"retcode":0,"message":"success","data":null}
url fetch responce: {"retcode":0,"message":"success","data":null}
url fetch responce: {"retcode":0,"message":"success","data":null}

**Comment by NotThorny** [comment]
The normal login screen would mean your proxy is off, double check that you have "Use Internal Proxy" checked in settings.
